# frozen_string_literal: true

require 'yaml/store'
require 'date'
require 'pry'
require_relative 'lib/modules/errors/error_empty_string'
require_relative 'lib/modules/errors/error_negative_or_zero'
require_relative 'lib/modules/errors/error_unexpected_class'
require_relative 'lib/modules/validator'
require_relative 'lib/entity/author'
require_relative 'lib/entity/book'
require_relative 'lib/entity/library'
require_relative 'lib/entity/order'
require_relative 'lib/entity/reader'
require_relative 'lib/entity/storage'
